services:
  - type: web
    name: meme-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn_config.py app:app
    envVars:
      - key: CLOUDINARY_URL
        sync: false 